
-include vendor/cm/config/common_versions.mk

#$(call inherit-product, device/samsung/smdkv210/device.mk)
$(call inherit-product, device/samsung/smdkv210/full_smdkv210.mk)


PRODUCT_RELEASE_NAME := Hotel
# Inherit some common evervolv stuff.
$(call inherit-product, vendor/cm/config/common_full_tablet_wifionly.mk)
#
# Setup device specific product configuration.
#
PRODUCT_NAME    := cm_smdkv210
PRODUCT_BRAND   := BenQ
PRODUCT_DEVICE  := smdkv210
PRODUCT_MANUFACTURER := BenQ

#default model is XiaoZ

PRODUCT_MODEL   := Xiaoz
CLOUDMONITOR_DEVICE_CODE :=0

ifeq ($(TARGET_CLOUDMONITOR_MODEL),Hotel)
PRODUCT_MODEL   := Hotel
CLOUDMONITOR_DEVICE_CODE :=1
endif

ifeq ($(TARGET_CLOUDMONITOR_MODEL),Internet)
PRODUCT_MODEL   := Internet
CLOUDMONITOR_DEVICE_CODE :=2
endif


PRODUCT_MOD_DEVICE := $(PRODUCT_MODEL)
PRODUCT_BUILD_PROP_OVERRIDES += \
PRODUCT_NAME=${PRODUCT_NAME} \
TARGET_DEVICE=${PRODUCT_MODEL} \
PRODUCT_MODEL="${PRODUCT_MODEL}" \
PRODUCT_BRAND=${PRODUCT_BRAND} \
PRODUCT_DEVICE=${PRODUCT_DEVICE} \
PRODUCT_INTERNAL_VENDOR_CODE=Z \
PRODUCT_INTERNAL_DEVICE_CODE=${CLOUDMONITOR_DEVICE_CODE} \
BUILD_FINGERPRINT="${PRODUCT_BRAND} ${PRODUCT_MODEL} ${PRODUCT_DEVICE} ${PLATFORM_VERSION} ${BUILD_ID} ${PRODUCT_VERSION_CODE}${BUILD_YEAR}.${BUILD_MONTH}.${BUILD_DAYS} ${UTC_DATE} ${TARGET_BUILD_VARIANT}test-keys" \
PRIVATE_BUILD_DESC="${PRODUCT_BRAND}/${PRODUCT_MODEL}/${PRODUCT_DEVICE}:${PLATFORM_VERSION}/${BUILD_ID}/${PRODUCT_VERSION_CODE}${BUILD_YEAR}.${BUILD_MONTH}.${BUILD_DAYS}/${UTC_DATE}:${TARGET_BUILD_VARIANT}/test-keys" \
PRODUCT_MOD_DEVICE=${PRODUCT_MOD_DEVICE}  




